# Librairies

In [86]:
import os
import pandas as pd

# Read File and get overall information of the dataframe

Read imported files
Sources : https://www.kaggle.com/teajay/global-shark-attacks

In [87]:
initial_data=pd.read_csv('/Users/sandrine/desktop/prework/Projects_Ironhack/Shark_lab/attacks.csv',encoding='latin-1')
# use encoding = 'Latin-1 '

In [88]:
initial_data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [89]:
#Number of rows and columns
initial_data.shape

(25723, 24)

In [90]:
# check DataFrame info
initial_data.info()

# all the columns at max 1/3 full=> there may be fully null rows in the dataframe
# 3 columns named Case Number==> check whether there are the same or not and whether it is necessary to keep them all.
# 2 Unnamed colums with almost no values . Check whether they can be deleted.
# Can species and time and age be used given the high level of missingg data?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

**Analyze the DataFrame general information before starting

In [91]:
# function checking the Frequency of the different elements in each column of a dataframe
def freq_element_percolumn(data):
    cols=data.columns
    for i in cols:
        freq_per_element=pd.Series(data[i]).value_counts(normalize=True)*100
        print(f'Column studied is : {i}')
        display(freq_per_element)
    return

#freq_element_percolumn(initial_data)

# CLEANING

In [7]:
# General cleaning:
# Clean column titles => to ease selection 
# delete empty rows and columns
# delete duplicated rows and columns
# check whether it is worth keepin 3 columns case number

 ° Clean column titles

In [92]:
initial_data.columns=pd.Series(list(initial_data.columns)).str.lower().str.title().str.replace(' ','_').str.replace('Sex_','Sex').str.replace('Species_','Species').str.replace(':','').str.replace('.','')
initial_data.head()

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order,Unnamed_22,Unnamed_23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [9]:
# Delete empty rows and columns

In [93]:
# drop rows if there is maximum 2 values in the row.
def Drop_almost_empty_rows(data):
    return data[data.isnull().sum(axis=1) <= len(data.columns) - 3]
data=Drop_almost_empty_rows(initial_data)
data

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order,Unnamed_22,Unnamed_23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case_Number             6301 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal_(Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator_Or_Source  6285 non-null   object
 16  Pdf                     6302 non-null   object
 17  Href_Formula            6301 non-null   object
 18  Href                    6302 non-null   object
 19  Case_Number1            6302 non-null   object
 20  Case_Number2            6302 non-null   object
 21  Original_Order          6302 non-null   float64
 22  Unnamed_22              1 non-null      object
 23  Unnamed_23              2 non-null      object
dtypes: float64(2), object(22)
memory usage: 1.2+ MB

In [95]:
#Deleting not necessary columns.
data=data.drop(['Unnamed_22','Unnamed_23'],axis=1)
data

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal_(Y/N),Time,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [96]:
# found on google: https://thispointer.com/how-to-find-drop-duplicate-columns-in-a-dataframe-python-pandas/
def get_duplicated_columns(data):        
    '''
    Get a list of duplicate columns.
    It will iterate over all the columns in dataframe and find the columns whose contents are duplicate.
    :param df: Dataframe object
    :return: List of columns whose contents are duplicates.
    '''
    duPcolumnNames = set()
    # Iterate over all the columns in dataframe
    for x in range(data.shape[1]):
        # Select column at xth index.
        col = data.iloc[:, x]
        # Iterate over all the columns in DataFrame from (x+1)th index till end
        for y in range(x+1,data.shape[1]):
            # Select column at yth index.
            otherCol = data.iloc[:, y]
            # Check if two columns at x 7 y index are equal
            if col.equals(otherCol):
                duPcolumnNames.add(data.columns.values[y])
    return list(duPcolumnNames)

get_duplicated_columns(data)
# no duplicated columns

[]

In [97]:
# check duplitated rows:
data=data.drop_duplicates()

In [ ]:
# Check the differences between 3 columns Case_Number ==> Not worth to be cleaned as not used.

In [98]:
def Check_Dup_Two_columns(data,col1,col2):
    
    CheckDup=list(data[col1]==data[col2])
    # Index where the the differences occurs
    indexDup=[i for i in range(len(CheckDup)) if CheckDup[i]==False] 
    print(f'position of duplicates elements for {col1} & {col2} is {indexDup}. There is {len(indexDup)} positions.')
    return indexDup

set1=set(Check_Dup_Two_columns(data,'Case_Number','Case_Number2'))
set2=set(Check_Dup_Two_columns(data,'Case_Number','Case_Number1'))
set3=set(Check_Dup_Two_columns(data,'Case_Number2','Case_Number1'))
print('to check', set1.union(set2).union(set3))

for i in set1.union(set2).union(set3):
    display(data.iloc[i])

position of duplicates elements for Case_Number & Case_Number2 is [390, 4949, 5488, 5944]. There is 4 positions.
position of duplicates elements for Case_Number & Case_Number1 is [34, 117, 144, 217, 314, 334, 339, 390, 560, 3522, 3795, 3880, 4403, 4425, 4949, 5275, 5358, 5386, 5488, 5777, 5883, 5944, 6009, 6122]. There is 24 positions.
position of duplicates elements for Case_Number2 & Case_Number1 is [34, 117, 144, 217, 314, 334, 339, 560, 3522, 3795, 3880, 4403, 4425, 5275, 5358, 5386, 5777, 5883, 6009, 6122]. There is 20 positions.
to check {390, 5386, 144, 5777, 5275, 34, 3880, 560, 4403, 5944, 314, 3522, 4425, 334, 339, 3795, 4949, 217, 6122, 5358, 5488, 117, 6009, 5883}

Case_Number                                                      2015.07-10
Date                                                            10-Jul-2015
Year                                                                   2015
Type                                                             Unprovoked
Country                                                                 USA
Area                                                             California
Location                                    Huntington Beach, Orange County
Activity                                                            Surfing
Name                                                           Danny Miskin
Sex                                                                       M
Age                                                                      38
Injury                              No injury, shark bumped & damaged board
Fatal_(Y/N)                                                               N
Time                                                                  08h45
Species                                                     White shark, 7'
Investigator_Or_Source                                      KTLA, 7/10/2015
Pdf                                                   2015.07.10-Miskin.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.07.10
Case_Number2                                                     2015.07.10
Original_Order                                                         5913
Name: 390, dtype: object

Case_Number                                                    1911.07.31.R
Date                                                   Reported 31-Jul-1911
Year                                                                   1911
Type                                                             Unprovoked
Country                                                               SPAIN
Area                                                                Málaga
Location                                                              Ceuta
Activity                                                            Bathing
Name                                                              a soldier
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore. GSAF
Pdf                                                  1911.07.31.R-Ceuta.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1911.07.31.T
Case_Number2                                                   1911.07.31.R
Original_Order                                                          917
Name: 5386, dtype: object

Case_Number                                                      2017.05.06
Date                                                            05-May-2017
Year                                                                   2017
Type                                                             Unprovoked
Country                                                              MEXICO
Area                                                    Baja California Sur
Location                                          Los Arbolitos, Cabo Pulmo
Activity                                                         Snorkeling
Name                                                          Andres Rozada
Sex                                                                       M
Age                                                                      33
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                  17h00
Species                                                                 NaN
Investigator_Or_Source                                            J. Rozada
Pdf                                                   2017.05.06-Rozada.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2017.06.06
Case_Number2                                                     2017.05.06
Original_Order                                                         6159
Name: 144, dtype: object

Case_Number                                                    1884.04.38.R
Date                                                   Reported 28-Apr-1884
Year                                                                   1884
Type                                                             Unprovoked
Country                                                              BRAZIL
Area                                                                    NaN
Location                                                              Bahia
Activity                            Fell overboard from the steamship Chala
Name                                                                   male
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                   Pittsburgh Post Gazette, 4/28/1884
Pdf                                              1884.04.28.R-ChalaCook.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1884.04.28.R
Case_Number2                                                   1884.04.38.R
Original_Order                                                          526
Name: 5777, dtype: object

Case_Number                                                    1900.00.00.R
Date                                   Reported to have taken place in 1919
Year                                                                   1919
Type                                                                Boating
Country                                                               ITALY
Area                                                                    NaN
Location                                                             Savona
Activity                                                            Fishing
Name                                                                    NaN
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           13' shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                 1919.00.00.R-Savona.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1919.00.00.R
Case_Number2                                                   1900.00.00.R
Original_Order                                                         1028
Name: 5275, dtype: object

Case_Number                                                      2018.04.03
Date                                                            03-Apr-2018
Year                                                                   2018
Type                                                             Unprovoked
Country                                                        SOUTH AFRICA
Area                                                  Eastern Cape Province
Location                                                    St. Francis Bay
Activity                                                            Surfing
Name                                                           Ross Spowart
Sex                                                                       M
Age                                                                      19
Injury                                 Lacerations to left knee & lower leg
Fatal_(Y/N)                                                               N
Time                                                                  15h00
Species                                                         White shark
Investigator_Or_Source                      K. McMurray, TrackingSharks.com
Pdf                                             2018.04.03-StFrancisBay.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2018.04.02
Case_Number2                                                     2018.04.03
Original_Order                                                         6269
Name: 34, dtype: object

Case_Number                                                    1961.09.02.R
Date                                                   Reported 06-Sep-1961
Year                                                                   1961
Type                                                               Provoked
Country                                                               ITALY
Area                                                        Venice Province
Location                                                           Chioggia
Activity                                                            Fishing
Name                                  Pollione Perrini & Fioravante Perini
Sex                                                                       M
Age                                                                 33 & 37
Injury                    Left foot & right hand bitten by netted shark ...
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           1 m shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                               1961.09.06.R-Chioggia.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1961.09,06.R
Case_Number2                                                   1961.09.02.R
Original_Order                                                         2423
Name: 3880, dtype: object

Case_Number                                                      2014.05.04
Date                                                            04-May-2014
Year                                                                   2014
Type                                                             Unprovoked
Country                                                        SOUTH AFRICA
Area                                                  Western Cape Province
Location                                                         Simonstown
Activity                                                             Diving
Name                                                                    NaN
Sex                                                                     NaN
Age                                                                     NaN
Injury                                             4-inch laceration to arm
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           Cow shark
Investigator_Or_Source                               Sunday Times, 5/5/2014
Pdf                                                 2015.05.04-CowShark.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2013.05.04
Case_Number2                                                     2014.05.04
Original_Order                                                         5743
Name: 560, dtype: object

Case_Number                                                      1952.08.05
Date                                                            05-Aug-1952
Year                                                                   1952
Type                                                               Provoked
Country                                                               ITALY
Area                                                                 Teramo
Location                                                         Giulianova
Activity                                                            Fishing
Name                                                         Vittorio Speca
Sex                                                                     NaN
Age                                                                      19
Injury                                  Multiple injuries PROVOKED INCIDENT
Fatal_(Y/N)                                                               Y
Time                                                                  02h00
Species                                                            2m shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                    1952.08.05-Speca.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1952.08.04
Case_Number2                                                     1952.08.05
Original_Order                                                         1900
Name: 4403, dtype: object

Case_Number                                                         1864.05
Date                                                               May-1864
Year                                                                   1864
Type                                                             Unprovoked
Country                                                           MAURITIUS
Area                                            300 miles east of Mauritius
Location                                                                NaN
Activity                                                     Fell overboard
Name                                         male from the whaler Albatross
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                    North Adams Transcript, 3/18/1898
Pdf                                                1864.05.00.Mauritius.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1864.05.00
Case_Number2                                                     1864.05.00
Original_Order                                                          359
Name: 5944, dtype: object

Case_Number                                                    2016.01.24.b
Date                                                            24-Jan-2016
Year                                                                   2016
Type                                                             Unprovoked
Country                                                                 USA
Area                                                                  Texas
Location                                                       Off Surfside
Activity                                                       Spearfishing
Name                                                             Keith Love
Sex                                                                       M
Age                                                                     NaN
Injury                    Bruised ribs & tail bone, speargun broken and ...
Fatal_(Y/N)                                                               N
Time                                                          09h30 / 10h00
Species                                                     Bull sharks x 2
Investigator_Or_Source                                              K. Love
Pdf                                                   2016.01.24.b-Love.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   2015.01.24.b
Case_Number2                                                   2016.01.24.b
Original_Order                                                         5989
Name: 314, dtype: object

Case_Number                                                      1967.07.05
Date                                                            05-Jul-1967
Year                                                                   1967
Type                                                             Unprovoked
Country                                                              TURKEY
Area                                                         Mugla Province
Location                                                    Kucukada Island
Activity                                                       Spearfishing
Name                                                           Gungor Guven
Sex                                                                       M
Age                                                                      36
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                  13h40
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                    1967.07.05-Guven.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1967/07.05
Case_Number2                                                     1967.07.05
Original_Order                                                         2781
Name: 3522, dtype: object

Case_Number                                                    1851.12.15.R
Date                                                         \n1951.12.15.R
Year                                                                   1951
Type                                                                Invalid
Country                                                          MOZAMBIQUE
Area                                                        Sofala Province
Location                                                              Beira
Activity                                                           Swimming
Name                                               Antonio De Almeida Pinto
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                             NaN
Time                                                                    NaN
Species                                                             Invalid
Investigator_Or_Source                                                 GSAF
Pdf                                                  1951.12.15.R-Pinto.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1951.12.15.R
Case_Number2                                                   1851.12.15.R
Original_Order                                                         1878
Name: 4425, dtype: object

Case_Number                                                      2015.12.23
Date                                                            07-Nov-2015
Year                                                                   2015
Type                                                                Invalid
Country                                                                 USA
Area                                                                Florida
Location                          Paradise Beach, Melbourne, Brevard County
Activity                                                            Surfing
Name                                                         Ryla Underwood
Sex                                                                       F
Age                                                                       9
Injury                                               Lower left leg injured
Fatal_(Y/N)                                                             NaN
Time                                                                  11h00
Species                                     Shark involvement not confirmed
Investigator_Or_Source                              Fox25Orlando, 11/7/2015
Pdf                                                2015.11.07-Underwood.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.11.07
Case_Number2                                                     2015.12.23
Original_Order                                                         5969
Name: 334, dtype: object

Case_Number                                                    2015.10.28.a
Date                                                            28-Oct-2015
Year                                                                   2015
Type                                                             Unprovoked
Country                                                                 USA
Area                                                                 Hawaii
Location                                                       Malaka, Oahu
Activity                                                      Body boarding
Name                                                        Raymond Senensi
Sex                                                                       M
Age                                                                      10
Injury                    Lacerations & puncture wounds to right thigh, ...
Fatal_(Y/N)                                                               N
Time                                                                  14h50
Species                                                                 NaN
Investigator_Or_Source                          Star Advertiser, 10/28/2015
Pdf                                                  2015.10.28-Senensi.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.10.28
Case_Number2                                                   2015.10.28.a
Original_Order                                                         5964
Name: 339, dtype: object

Case_Number                                                    1962,08.30.b
Date                                                            30-Aug-1962
Year                                                                   1962
Type                                                                   Boat
Country                                                              TURKEY
Area                                                       Antalya Province
Location                                                             Ucagiz
Activity                                                                NaN
Name                                                   Occupant: Hasan Olta
Sex                                                                       M
Age                                                                     NaN
Injury                                                           No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                        C.Moore, GSAF
Pdf                                                        1962.08.30.b-pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1962.08.30.b
Case_Number2                                                   1962,08.30.b
Original_Order                                                         2508
Name: 3795, dtype: object

Case_Number                                                    1934.01.08.R
Date                                                   Reported 08-Feb-1934
Year                                                                   1934
Type                                                                Boating
Country                                                              TURKEY
Area                                                               Istanbul
Location                                         Haydarpasa jetty, Istanbul
Activity                                                            Fishing
Name                                                                2 males
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                 1924.02.08.R-Turkey.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1934.02.08.R
Case_Number2                                                   1934.02.08.R
Original_Order                                                         1354
Name: 4949, dtype: object

Case_Number                                                      2016.09.15
Date                                                            16-Sep-2016
Year                                                                   2016
Type                                                             Unprovoked
Country                                                           AUSTRALIA
Area                                                               Victoria
Location                                                        Bells Beach
Activity                                                            Surfing
Name                                                                   male
Sex                                                                       M
Age                                                                     NaN
Injury                                No injury: Knocked off board by shark
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           2 m shark
Investigator_Or_Source                                   The Age, 9/16/2016
Pdf                                               2016.09.16-BellsBeach.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2016.09.16
Case_Number2                                                     2016.09.15
Original_Order                                                         6086
Name: 217, dtype: object

Case_Number                                                    1808.06.01.R
Date                                                   Reported 01-May-1808
Year                                                                   1808
Type                                                           Sea Disaster
Country                                                             ANTIGUA
Area                                                                    NaN
Location                                                   Falmouth Harbour
Activity                                                                NaN
Name                                                                    NaN
Sex                                                                     NaN
Age                                                                     NaN
Injury                                       Probable drowning & scavenging
Fatal_(Y/N)                                                             NaN
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                            London Observer, 5/1/1808
Pdf                                                1808.05.01.R-Antigua.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1808.05.01.R
Case_Number2                                                   1808.06.01.R
Original_Order                                                          181
Name: 6122, dtype: object

Case_Number                                                    1913.07.10.R
Date                                                   Reported 10-Jul-1913
Year                                                                   1913
Type                                                             Unprovoked
Country                                                          COSTA RICA
Area                                                                    NaN
Location                                                         Port Limon
Activity                                                           Swimming
Name                                          August Schulke & Karl Schafer
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                     The Potter Enterprise, 7/10/1913
Pdf                                              1913.07.10.R-PortLimon.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1913.17.10.R
Case_Number2                                                   1913.07.10.R
Original_Order                                                          945
Name: 5358, dtype: object

Case_Number                                                             NaN
Date                                                   Reported 06-Sep-1905
Year                                                                   1905
Type                                                               Provoked
Country                                                                 USA
Area                                                                Florida
Location                                       Fort Pierce, St Lucie County
Activity                                                            Fishing
Name                                                            David Curry
Sex                                                                       M
Age                                                                     NaN
Injury                    Lacerations to leg from hooked shark PROVOKED ...
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                       Muncie Evening Press, 8/6/1913
Pdf                                                  1905.09.06.R-Curry.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1905.09.06.R
Case_Number2                                                   1905.09.06.R
Original_Order                                                          815
Name: 5488, dtype: object

Case_Number                                                    2017.07.20.a
Date                                                            20-Jul-2017
Year                                                                   2017
Type                                                             Unprovoked
Country                                                                 USA
Area                                                             California
Location                             Seal Rock, Goleta Beach, Santa Barbara
Activity                                                                SUP
Name                                                           Rolf Geyling
Sex                                                                       M
Age                                                                      50
Injury                                     No injury, shark bit paddleboard
Fatal_(Y/N)                                                               N
Time                                                                  07h45
Species                                              White shark, 8' to 10'
Investigator_Or_Source                                     R. Collier, GSAF
Pdf                                                2017.07.20.a-Geyling.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   2017/07.20.a
Case_Number2                                                   2017.07.20.a
Original_Order                                                         6186
Name: 117, dtype: object

Case_Number                                                      1853,94.29
Date                                                            29-Apr-1853
Year                                                                   1853
Type                                                             Unprovoked
Country                                                              GREECE
Area                                                                 Corfu
Location                                                                NaN
Activity                                                           Swimming
Name                                                                 Hanson
Sex                                                                       M
Age                                                                     NaN
Injury                                                  Leg severed at knee
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                        234-lb shark
Investigator_Or_Source                  South Australian Register, 5/8/1854
Pdf                                                   1853.04.29-Hanson.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1853.04.29
Case_Number2                                                     1853,94.29
Original_Order                                                          294
Name: 6009, dtype: object

Case_Number                                                    1876.06.18.R
Date                                                  Reported 18-Jun- 1874
Year                                                                   1874
Type                                                             Unprovoked
Country                                                              MEXICO
Area                                                              Veracruz
Location                                             Tlacotalpan, Vera Cruz
Activity                                                            Bathing
Name                                              a servant of General Diaz
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                        The Times-Picayune, 6/18/1874
Pdf                                            1874.06.18.R-DiazServant.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1874.06.18.R
Case_Number2                                                   1876.06.18.R
Original_Order                                                          420
Name: 5883, dtype: object

# Cleaning linked to the problematics

problematics:
* trtr
* trt

#TO DO : Clean Year, fatal Area maybe activity

In [ ]:
# questions to answer : When and where and for which activity were the most fatal attacks /

#Cleaning of column Year

In [107]:
#Let's have a look to the values in the column to clean 
data.Year.dtype

dtype('float64')

In [109]:
def get_basic_info_for_column(data,col):
    #check frequency of each element of the column (in %)
    display(pd.Series(data[col]).value_counts(normalize=True)*100)
    #print the min and the max for numeric data
    if data[col].dtype=='float64' or  data[col].dtype=='int':
        print('Min & Max', min(data[col]), max(data[col]))
    #how many missing data in Year column?:
    print('nb of missing values' ,data[col].isnull().sum())
    return None
get_basic_info_for_column(data,'Year')

2015.0    2.269841
2017.0    2.158730
2016.0    2.063492
2011.0    2.031746
2014.0    2.015873
            ...
1801.0    0.015873
1638.0    0.015873
1834.0    0.015873
1723.0    0.015873
1786.0    0.015873
Name: Year, Length: 249, dtype: float64

Min & Max 0.0 2018.0
nb of missing values 2

In [50]:
# isolate missing values in column Year and display the associated rows
data[data.Year.isnull()]
# 2 rows concerned: n87 and 6079.
# First find the year using the  reported date 
#check whether other field in the row have an issue, especially the columns you are interested in  and clean them if possible
# at the same time
#Second use the pdf to fill in the missing information if necessary.

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal_(Y/N),Time,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order
187,2017.01.08.R,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,...,NaN,NaN,Bull shark,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6116.0
6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,224.0

In [54]:
data.Year.iloc[187]=2017
data['Fatal_(Y/N)'].iloc[187]='N'
data.Year.iloc[6079]=1836
data['Href_Formula'].iloc[6079]='http://www.sharkattackfile.net/spreadsheets/pdf_directory/1836.08.19.R-Whitehaven.pdf'
data['Href'].iloc[6079]='http://www.sharkattackfile.net/spreadsheets/pdf_directory/1836.08.19.R-Whitehaven.pdf'
data['Fatal_(Y/N)'].iloc[6079]='Y'
#check if there are still missing values
data[data.Year.isnull()]
#drop remaining rows by selecting the none null values of years
data=data[data.Year.notnull()]
# select the Year =0
data[data.Year==0] # 125 rows with a year =0 vs 6300 records. 1%. To be treated if sufficient time
# display date column  for Year =0 to see wether the year appear in the date
pd.Series(data[data.Year==0].Date).value_counts() # compare with the year of full set. 
#Check the number of rows if we do buckets like 'before 1960 (2500 rows more than 1/3 of therows , before 1920)
# 125 rows with no exact date no change for the moment . Doing
data[data.Year==0].Date.to_list() # put the date for Year ==0 to see whether some records could be treated 
data[data.Year==0]

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Fatal_(Y/N),Time,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order
6177,0000.0214,Ca. 214 B.C.,0.0,Unprovoked,NaN,Ionian Sea,NaN,Ascending from a dive,"Tharsys, a sponge diver",M,...,Y,NaN,NaN,"Reported by Greek poet, Leonidas of Tarentum (...",214BC-Tharsys.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0214,0000.0214,126.0
6178,0000.0336,Ca. 336.B.C..,0.0,Unprovoked,GREECE,Piraeus,In the haven of Cantharus,Washing his pig in preparation for a religious...,A candidate for initiation,M,...,Y,NaN,NaN,Plutarch (45 - 125 A.D.) in Life of Phoecion (...,336-BC-Carnathus.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0336,0000.0336,125.0
6179,0000.0493,493 B.C.,0.0,Sea Disaster,GREECE,Off Thessaly,NaN,Shipwrecked Persian Fleet,males,M,...,Y,NaN,NaN,Herodotus (485 - 425 B.C.),493BC-PersianFleet.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0493,0000.0493,124.0
6180,0000.0725,Ca. 725 B.C.,0.0,Sea Disaster,ITALY,Tyrrhenian Sea,Krater found during excavations at Lacco Ameno...,Shipwreck,males,M,...,Y,NaN,NaN,"V.M. Coppleson (1958), p.262, et al",725BC-vase.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0000.0725,0000.0725,123.0
6181,ND-0154,Before 1939,0.0,Unprovoked,CANADA,NaN,Grand Banks,Fishing,Joe Folsom,M,...,N,NaN,NaN,"C.E.Russell, pp. 310-311",ND-0154-Folsom.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND-0154,ND-0154,122.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

Cleaning Fatal column

In [85]:
data[data['Fatal_(Y/N)'=='M']]

KeyError: False

In [82]:

data['Fatal_(Y/N)']=data['Fatal_(Y/N)'].str.upper().replace('M','N').replace(' N','N').replace('N ','N')
display(pd.Series(data['Fatal_(Y/N)']).value_counts(normalize=True)*100)

N          74.653019
Y          24.097849
UNKNOWN     1.231783
2017        0.017349
Name: Fatal_(Y/N), dtype: float64

Cleaning Species columns

In [ ]:
new_data[new_data.Species].value_counts(normalize=True)*100

In [ ]:
new_data.Species.count()

# Helpfull formulas

In [ ]:
# vérifier s'il y a des donnees manquantes dans les colonnes
initial_data.columns[initial_data.isnull().any()]

In [ ]:
new_data[new_data["Year"] < 1920]

In [ ]:
# Replace NaN float to integer 0 in numeric table
#new_data['Year'].apply(int)

In [ ]:
new_data['href formula'].iloc[187]

In [ ]:
new_data[new_data.Year.isnull()]

In [ ]:
new_data.iloc[6079]

In [ ]:
new_data.Year.iloc[1]

In [ ]:
new_data['href'].iloc[6079]

In [ ]:
#appeler les lignes pour lesquelles year =1999
set=new_data[new_data["Year"] == 1999]

In [ ]:
pd.Series(list(new_data.columns)).str.lower().str.title().str.replace(' ','_').str.replace('Sex_','Sex').str.replace('Species_','Species')

In [ ]:
#Nbre de données manquantes par colonne/ Doublon avec infor
# Number of missing values per column . Other way to read 

initial_data.isnull().sum(axis=1)
# Lots of null values in all the columns==> there may be null rows
# columns named Case Number+> check whether there are the same or not
# 2 Unnamed colums with almost no values . Check whether they can be deleted.
# Can species and time and age  be used given the high level of missingg data?

In [ ]:
# filter the rows with less than two non "null" columns.
# a column is null if it equals Nan, '', 0 or '0'
import numpy as np
data[data.replace(['', 0, '0'], np.nan).isnull().sum(axis=1) <= len(data.columns) - 2]

In [ ]:
#Delete all rows with missing values for all rows
data=initial_data.dropna(axis=0,how='all')
data.shape # 8703 rows remain out of 25723. displaying data I notice that there where case number at 0 with no information
#remove empty rows ignoring the column case number
data.columns
data.dropna(axis=0,how='all',subset=['Date', 'Year', 'Type', 'Country', 'Area', 'Location','Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal_(Y/N)', 'Time','Species', 'Investigator_Or_Source', 'Pdf', 'Href_Formula', 'Href','Case_Number1', 'Case_Number2', 'Original_Order', 'Unnamed_22','Unnamed_23'])
#remove empty rows ignoring the column 'case number1' as there are rows with only  one value in this colon