# Librairies

In [5]:
import os
import pandas as pd

# Read File and get overall information of the dataframe

Read imported files
Sources : https://www.kaggle.com/teajay/global-shark-attacks

In [6]:
initial_data=pd.read_csv('/Users/sandrine/desktop/prework/Projects_Ironhack/Shark_lab/attacks.csv',encoding='latin-1')
# use encoding = 'Latin-1 '

In [7]:
initial_data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [8]:
#Number of rows and columns
initial_data.shape

(25723, 24)

In [9]:
# check DataFrame info
initial_data.info()

# all the columns at max 1/3 full=> there may be fully null rows in the dataframe
# 3 columns named Case Number==> check whether there are the same or not and whether it is necessary to keep them all.
# 2 Unnamed colums with almost no values . Check whether they can be deleted.
# Can species and time and age be used given the high level of missingg data?

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

**Analyze the DataFrame general information before starting

In [10]:
# function checking the Frequency of the different elements in each column of a dataframe
def freq_element_percolumn(data):
    cols=data.columns
    for i in cols:
        freq_per_element=pd.Series(data[i]).value_counts(normalize=True)*100
        print(f'Column studied is : {i}')
        display(freq_per_element)
    return

#freq_element_percolumn(initial_data)

# CLEANING

In [ ]:
# General cleaning:
# Clean column titles => to ease selection 
# delete empty rows and columns
# delete duplicated rows and columns
# check whether it is worth keepin 3 columns case number

 ° Clean column titles

In [11]:
initial_data.columns=pd.Series(list(initial_data.columns)).str.lower().str.title().str.replace(' ','_').str.replace('Sex_','Sex').str.replace('Species_','Species').str.replace(':','').str.replace('.','')
initial_data.head()

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order,Unnamed_22,Unnamed_23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [12]:
# Delete empty rows and columns

In [14]:
# drop rows if there is maximum 2 values in the row.
def Drop_almost_empty_rows(data):
    return data[data.isnull().sum(axis=1) <= len(data.columns) - 3]
data=Drop_almost_empty_rows(initial_data)
data

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order,Unnamed_22,Unnamed_23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case_Number             6301 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal_(Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator_Or_Source  6285 non-null   object
 16  Pdf                     6302 non-null   object
 17  Href_Formula            6301 non-null   object
 18  Href                    6302 non-null   object
 19  Case_Number1            6302 non-null   object
 20  Case_Number2            6302 non-null   object
 21  Original_Order          6302 non-null   float64
 22  Unnamed_22              1 non-null      object
 23  Unnamed_23              2 non-null      object
dtypes: float64(2), object(22)
memory usage: 1.2+ MB

In [ ]:
#Deleting not necessary columns.
data=data.drop(['Unnamed_22','Unnamed_23'],axis=1)
data

In [16]:
# found on google: https://thispointer.com/how-to-find-drop-duplicate-columns-in-a-dataframe-python-pandas/
def get_duplicated_columns(data):        
    '''
    Get a list of duplicate columns.
    It will iterate over all the columns in dataframe and find the columns whose contents are duplicate.
    :param df: Dataframe object
    :return: List of columns whose contents are duplicates.
    '''
    duPcolumnNames = set()
    # Iterate over all the columns in dataframe
    for x in range(data.shape[1]):
        # Select column at xth index.
        col = data.iloc[:, x]
        # Iterate over all the columns in DataFrame from (x+1)th index till end
        for y in range(x+1,data.shape[1]):
            # Select column at yth index.
            otherCol = data.iloc[:, y]
            # Check if two columns at x 7 y index are equal
            if col.equals(otherCol):
                duPcolumnNames.add(data.columns.values[y])
    return list(duPcolumnNames)

get_duplicated_columns(data)
# no duplicated columns

[]

In [17]:
# check duplitated rows:
data=data.drop_duplicates()

In [ ]:
# Check the differences between 3 columns Case_Number ==> Not worth to be cleaned as not used.

In [19]:
def Check_Dup_Two_columns(data,col1,col2):
    
    CheckDup=list(data[col1]==data[col2])
    # Index where the the differences occurs
    indexDup=[i for i in range(len(CheckDup)) if CheckDup[i]==False] 
    print(f'position of duplicates elements for {col1} & {col2} is {indexDup}. There is {len(indexDup)} positions.')
    return indexDup

set1=set(Check_Dup_Two_columns(data,'Case_Number','Case_Number2'))
set2=set(Check_Dup_Two_columns(data,'Case_Number','Case_Number1'))
set3=set(Check_Dup_Two_columns(data,'Case_Number2','Case_Number1'))
print('to check', set1.union(set2).union(set3))

for i in set1.union(set2).union(set3):
    display(data.loc[i])

position of duplicates elements for Case_Number & Case_Number2 is [390, 4949, 5488, 5944]. There is 4 positions.
position of duplicates elements for Case_Number & Case_Number1 is [34, 117, 144, 217, 314, 334, 339, 390, 560, 3522, 3795, 3880, 4403, 4425, 4949, 5275, 5358, 5386, 5488, 5777, 5883, 5944, 6009, 6122]. There is 24 positions.
position of duplicates elements for Case_Number2 & Case_Number1 is [34, 117, 144, 217, 314, 334, 339, 560, 3522, 3795, 3880, 4403, 4425, 5275, 5358, 5386, 5777, 5883, 6009, 6122]. There is 20 positions.
to check {390, 5386, 144, 5777, 5275, 34, 3880, 560, 4403, 5944, 314, 3522, 4425, 334, 339, 3795, 4949, 217, 6122, 5358, 5488, 117, 6009, 5883}

Case_Number                                                      2015.07-10
Date                                                            10-Jul-2015
Year                                                                   2015
Type                                                             Unprovoked
Country                                                                 USA
Area                                                             California
Location                                    Huntington Beach, Orange County
Activity                                                            Surfing
Name                                                           Danny Miskin
Sex                                                                       M
Age                                                                      38
Injury                              No injury, shark bumped & damaged board
Fatal_(Y/N)                                                               N
Time                                                                  08h45
Species                                                     White shark, 7'
Investigator_Or_Source                                      KTLA, 7/10/2015
Pdf                                                   2015.07.10-Miskin.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.07.10
Case_Number2                                                     2015.07.10
Original_Order                                                         5913
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 390, dtype: object

Case_Number                                                    1911.07.31.R
Date                                                   Reported 31-Jul-1911
Year                                                                   1911
Type                                                             Unprovoked
Country                                                               SPAIN
Area                                                                Málaga
Location                                                              Ceuta
Activity                                                            Bathing
Name                                                              a soldier
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore. GSAF
Pdf                                                  1911.07.31.R-Ceuta.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1911.07.31.T
Case_Number2                                                   1911.07.31.R
Original_Order                                                          917
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5386, dtype: object

Case_Number                                                      2017.05.06
Date                                                            05-May-2017
Year                                                                   2017
Type                                                             Unprovoked
Country                                                              MEXICO
Area                                                    Baja California Sur
Location                                          Los Arbolitos, Cabo Pulmo
Activity                                                         Snorkeling
Name                                                          Andres Rozada
Sex                                                                       M
Age                                                                      33
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                  17h00
Species                                                                 NaN
Investigator_Or_Source                                            J. Rozada
Pdf                                                   2017.05.06-Rozada.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2017.06.06
Case_Number2                                                     2017.05.06
Original_Order                                                         6159
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 144, dtype: object

Case_Number                                                    1884.04.38.R
Date                                                   Reported 28-Apr-1884
Year                                                                   1884
Type                                                             Unprovoked
Country                                                              BRAZIL
Area                                                                    NaN
Location                                                              Bahia
Activity                            Fell overboard from the steamship Chala
Name                                                                   male
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                   Pittsburgh Post Gazette, 4/28/1884
Pdf                                              1884.04.28.R-ChalaCook.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1884.04.28.R
Case_Number2                                                   1884.04.38.R
Original_Order                                                          526
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5777, dtype: object

Case_Number                                                    1900.00.00.R
Date                                   Reported to have taken place in 1919
Year                                                                   1919
Type                                                                Boating
Country                                                               ITALY
Area                                                                    NaN
Location                                                             Savona
Activity                                                            Fishing
Name                                                                    NaN
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           13' shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                 1919.00.00.R-Savona.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1919.00.00.R
Case_Number2                                                   1900.00.00.R
Original_Order                                                         1028
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5275, dtype: object

Case_Number                                                      2018.04.03
Date                                                            03-Apr-2018
Year                                                                   2018
Type                                                             Unprovoked
Country                                                        SOUTH AFRICA
Area                                                  Eastern Cape Province
Location                                                    St. Francis Bay
Activity                                                            Surfing
Name                                                           Ross Spowart
Sex                                                                       M
Age                                                                      19
Injury                                 Lacerations to left knee & lower leg
Fatal_(Y/N)                                                               N
Time                                                                  15h00
Species                                                         White shark
Investigator_Or_Source                      K. McMurray, TrackingSharks.com
Pdf                                             2018.04.03-StFrancisBay.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2018.04.02
Case_Number2                                                     2018.04.03
Original_Order                                                         6269
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 34, dtype: object

Case_Number                                                    1961.09.02.R
Date                                                   Reported 06-Sep-1961
Year                                                                   1961
Type                                                               Provoked
Country                                                               ITALY
Area                                                        Venice Province
Location                                                           Chioggia
Activity                                                            Fishing
Name                                  Pollione Perrini & Fioravante Perini
Sex                                                                       M
Age                                                                 33 & 37
Injury                    Left foot & right hand bitten by netted shark ...
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           1 m shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                               1961.09.06.R-Chioggia.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1961.09,06.R
Case_Number2                                                   1961.09.02.R
Original_Order                                                         2423
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 3880, dtype: object

Case_Number                                                      2014.05.04
Date                                                            04-May-2014
Year                                                                   2014
Type                                                             Unprovoked
Country                                                        SOUTH AFRICA
Area                                                  Western Cape Province
Location                                                         Simonstown
Activity                                                             Diving
Name                                                                    NaN
Sex                                                                     NaN
Age                                                                     NaN
Injury                                             4-inch laceration to arm
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           Cow shark
Investigator_Or_Source                               Sunday Times, 5/5/2014
Pdf                                                 2015.05.04-CowShark.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2013.05.04
Case_Number2                                                     2014.05.04
Original_Order                                                         5743
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 560, dtype: object

Case_Number                                                      1952.08.05
Date                                                            05-Aug-1952
Year                                                                   1952
Type                                                               Provoked
Country                                                               ITALY
Area                                                                 Teramo
Location                                                         Giulianova
Activity                                                            Fishing
Name                                                         Vittorio Speca
Sex                                                                     NaN
Age                                                                      19
Injury                                  Multiple injuries PROVOKED INCIDENT
Fatal_(Y/N)                                                               Y
Time                                                                  02h00
Species                                                            2m shark
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                    1952.08.05-Speca.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1952.08.04
Case_Number2                                                     1952.08.05
Original_Order                                                         1900
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 4403, dtype: object

Case_Number                                                         1864.05
Date                                                               May-1864
Year                                                                   1864
Type                                                             Unprovoked
Country                                                           MAURITIUS
Area                                            300 miles east of Mauritius
Location                                                                NaN
Activity                                                     Fell overboard
Name                                         male from the whaler Albatross
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                    North Adams Transcript, 3/18/1898
Pdf                                                1864.05.00.Mauritius.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1864.05.00
Case_Number2                                                     1864.05.00
Original_Order                                                          359
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5944, dtype: object

Case_Number                                                    2016.01.24.b
Date                                                            24-Jan-2016
Year                                                                   2016
Type                                                             Unprovoked
Country                                                                 USA
Area                                                                  Texas
Location                                                       Off Surfside
Activity                                                       Spearfishing
Name                                                             Keith Love
Sex                                                                       M
Age                                                                     NaN
Injury                    Bruised ribs & tail bone, speargun broken and ...
Fatal_(Y/N)                                                               N
Time                                                          09h30 / 10h00
Species                                                     Bull sharks x 2
Investigator_Or_Source                                              K. Love
Pdf                                                   2016.01.24.b-Love.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   2015.01.24.b
Case_Number2                                                   2016.01.24.b
Original_Order                                                         5989
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 314, dtype: object

Case_Number                                                      1967.07.05
Date                                                            05-Jul-1967
Year                                                                   1967
Type                                                             Unprovoked
Country                                                              TURKEY
Area                                                         Mugla Province
Location                                                    Kucukada Island
Activity                                                       Spearfishing
Name                                                           Gungor Guven
Sex                                                                       M
Age                                                                      36
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                  13h40
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                    1967.07.05-Guven.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1967/07.05
Case_Number2                                                     1967.07.05
Original_Order                                                         2781
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 3522, dtype: object

Case_Number                                                    1851.12.15.R
Date                                                         \n1951.12.15.R
Year                                                                   1951
Type                                                                Invalid
Country                                                          MOZAMBIQUE
Area                                                        Sofala Province
Location                                                              Beira
Activity                                                           Swimming
Name                                               Antonio De Almeida Pinto
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                             NaN
Time                                                                    NaN
Species                                                             Invalid
Investigator_Or_Source                                                 GSAF
Pdf                                                  1951.12.15.R-Pinto.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1951.12.15.R
Case_Number2                                                   1851.12.15.R
Original_Order                                                         1878
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 4425, dtype: object

Case_Number                                                      2015.12.23
Date                                                            07-Nov-2015
Year                                                                   2015
Type                                                                Invalid
Country                                                                 USA
Area                                                                Florida
Location                          Paradise Beach, Melbourne, Brevard County
Activity                                                            Surfing
Name                                                         Ryla Underwood
Sex                                                                       F
Age                                                                       9
Injury                                               Lower left leg injured
Fatal_(Y/N)                                                             NaN
Time                                                                  11h00
Species                                     Shark involvement not confirmed
Investigator_Or_Source                              Fox25Orlando, 11/7/2015
Pdf                                                2015.11.07-Underwood.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.11.07
Case_Number2                                                     2015.12.23
Original_Order                                                         5969
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 334, dtype: object

Case_Number                                                    2015.10.28.a
Date                                                            28-Oct-2015
Year                                                                   2015
Type                                                             Unprovoked
Country                                                                 USA
Area                                                                 Hawaii
Location                                                       Malaka, Oahu
Activity                                                      Body boarding
Name                                                        Raymond Senensi
Sex                                                                       M
Age                                                                      10
Injury                    Lacerations & puncture wounds to right thigh, ...
Fatal_(Y/N)                                                               N
Time                                                                  14h50
Species                                                                 NaN
Investigator_Or_Source                          Star Advertiser, 10/28/2015
Pdf                                                  2015.10.28-Senensi.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2015.10.28
Case_Number2                                                   2015.10.28.a
Original_Order                                                         5964
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 339, dtype: object

Case_Number                                                    1962,08.30.b
Date                                                            30-Aug-1962
Year                                                                   1962
Type                                                                   Boat
Country                                                              TURKEY
Area                                                       Antalya Province
Location                                                             Ucagiz
Activity                                                                NaN
Name                                                   Occupant: Hasan Olta
Sex                                                                       M
Age                                                                     NaN
Injury                                                           No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                        C.Moore, GSAF
Pdf                                                        1962.08.30.b-pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1962.08.30.b
Case_Number2                                                   1962,08.30.b
Original_Order                                                         2508
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 3795, dtype: object

Case_Number                                                    1934.01.08.R
Date                                                   Reported 08-Feb-1934
Year                                                                   1934
Type                                                                Boating
Country                                                              TURKEY
Area                                                               Istanbul
Location                                         Haydarpasa jetty, Istanbul
Activity                                                            Fishing
Name                                                                2 males
Sex                                                                       M
Age                                                                     NaN
Injury                                                            No injury
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                                       C. Moore, GSAF
Pdf                                                 1924.02.08.R-Turkey.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1934.02.08.R
Case_Number2                                                   1934.02.08.R
Original_Order                                                         1354
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 4949, dtype: object

Case_Number                                                      2016.09.15
Date                                                            16-Sep-2016
Year                                                                   2016
Type                                                             Unprovoked
Country                                                           AUSTRALIA
Area                                                               Victoria
Location                                                        Bells Beach
Activity                                                            Surfing
Name                                                                   male
Sex                                                                       M
Age                                                                     NaN
Injury                                No injury: Knocked off board by shark
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                           2 m shark
Investigator_Or_Source                                   The Age, 9/16/2016
Pdf                                               2016.09.16-BellsBeach.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     2016.09.16
Case_Number2                                                     2016.09.15
Original_Order                                                         6086
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 217, dtype: object

Case_Number                                                    1808.06.01.R
Date                                                   Reported 01-May-1808
Year                                                                   1808
Type                                                           Sea Disaster
Country                                                             ANTIGUA
Area                                                                    NaN
Location                                                   Falmouth Harbour
Activity                                                                NaN
Name                                                                    NaN
Sex                                                                     NaN
Age                                                                     NaN
Injury                                       Probable drowning & scavenging
Fatal_(Y/N)                                                             NaN
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                            London Observer, 5/1/1808
Pdf                                                1808.05.01.R-Antigua.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1808.05.01.R
Case_Number2                                                   1808.06.01.R
Original_Order                                                          181
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 6122, dtype: object

Case_Number                                                    1913.07.10.R
Date                                                   Reported 10-Jul-1913
Year                                                                   1913
Type                                                             Unprovoked
Country                                                          COSTA RICA
Area                                                                    NaN
Location                                                         Port Limon
Activity                                                           Swimming
Name                                          August Schulke & Karl Schafer
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                     The Potter Enterprise, 7/10/1913
Pdf                                              1913.07.10.R-PortLimon.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1913.17.10.R
Case_Number2                                                   1913.07.10.R
Original_Order                                                          945
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5358, dtype: object

Case_Number                                                             NaN
Date                                                   Reported 06-Sep-1905
Year                                                                   1905
Type                                                               Provoked
Country                                                                 USA
Area                                                                Florida
Location                                       Fort Pierce, St Lucie County
Activity                                                            Fishing
Name                                                            David Curry
Sex                                                                       M
Age                                                                     NaN
Injury                    Lacerations to leg from hooked shark PROVOKED ...
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                       Muncie Evening Press, 8/6/1913
Pdf                                                  1905.09.06.R-Curry.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1905.09.06.R
Case_Number2                                                   1905.09.06.R
Original_Order                                                          815
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5488, dtype: object

Case_Number                                                    2017.07.20.a
Date                                                            20-Jul-2017
Year                                                                   2017
Type                                                             Unprovoked
Country                                                                 USA
Area                                                             California
Location                             Seal Rock, Goleta Beach, Santa Barbara
Activity                                                                SUP
Name                                                           Rolf Geyling
Sex                                                                       M
Age                                                                      50
Injury                                     No injury, shark bit paddleboard
Fatal_(Y/N)                                                               N
Time                                                                  07h45
Species                                              White shark, 8' to 10'
Investigator_Or_Source                                     R. Collier, GSAF
Pdf                                                2017.07.20.a-Geyling.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   2017/07.20.a
Case_Number2                                                   2017.07.20.a
Original_Order                                                         6186
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 117, dtype: object

Case_Number                                                      1853,94.29
Date                                                            29-Apr-1853
Year                                                                   1853
Type                                                             Unprovoked
Country                                                              GREECE
Area                                                                 Corfu
Location                                                                NaN
Activity                                                           Swimming
Name                                                                 Hanson
Sex                                                                       M
Age                                                                     NaN
Injury                                                  Leg severed at knee
Fatal_(Y/N)                                                               N
Time                                                                    NaN
Species                                                        234-lb shark
Investigator_Or_Source                  South Australian Register, 5/8/1854
Pdf                                                   1853.04.29-Hanson.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                     1853.04.29
Case_Number2                                                     1853,94.29
Original_Order                                                          294
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 6009, dtype: object

Case_Number                                                    1876.06.18.R
Date                                                  Reported 18-Jun- 1874
Year                                                                   1874
Type                                                             Unprovoked
Country                                                              MEXICO
Area                                                              Veracruz
Location                                             Tlacotalpan, Vera Cruz
Activity                                                            Bathing
Name                                              a servant of General Diaz
Sex                                                                       M
Age                                                                     NaN
Injury                                                                FATAL
Fatal_(Y/N)                                                               Y
Time                                                                    NaN
Species                                                                 NaN
Investigator_Or_Source                        The Times-Picayune, 6/18/1874
Pdf                                            1874.06.18.R-DiazServant.pdf
Href_Formula              http://sharkattackfile.net/spreadsheets/pdf_di...
Href                      http://sharkattackfile.net/spreadsheets/pdf_di...
Case_Number1                                                   1874.06.18.R
Case_Number2                                                   1876.06.18.R
Original_Order                                                          420
Unnamed_22                                                              NaN
Unnamed_23                                                              NaN
Name: 5883, dtype: object

# Cleaning linked to the problematics

problematics:
* trtr
* trt

#TO DO : Clean Year, fatal Area maybe activity

In [ ]:
# questions to answer : When and where and for which activity were the most fatal attacks /

In [31]:
# Function to get the some information about the column
def get_basic_info_for_column(data,col):
    #check frequency of each element of the column (in %)
    display(pd.Series(data[col]).value_counts(normalize=True)*100)
    #print the min and the max for numeric data
    if data[col].dtype=='float64' or  data[col].dtype=='int':
        print('Min & Max', min(data[col]), max(data[col]))
    #how many missing data in Year column?:
    print('nb of missing values' ,data[col].isnull().sum())
    return None

# Partial cleaning Species column

In [ ]:
#trying to identify invalid rows using species to go faster in the cleaning of Fatal column(from 538 to 62 missing values to clean)

In [21]:
get_basic_info_for_column(data,'Species' )
data.Species=data.Species=data.Species.str.lower().str.replace(' ','_').replace(['shark_involvement_questionable','questionable_incident','shark_involvement_prior_to_death_was_not_confirmed','shark_involvement_not_confirmed','shark_involvement_prior_to_death_unconfirmed','questionable','no_shark_involvement','shark_involvement_prior_to_death_not_confirmed', 'shark_involvement_prior_to_death_suspected_but_not_confirmed','shark_involvement_probable','shark_involvement_doubtful','shark_involvement_not_cofirmed',"thought_to_involve_a_3'_to_4'_shark,_but_shark_involvement_not_confirmed",'shark_involvement_unconfirmed','shark_involvement_prior_to_death_still_to_be_determined','shark_involvement_not_confirmed;_thought_to_be_a_barracuda_bite','shark_involvement_prior_to_deaths_was_not_confirmed','reported_by_media_as_shark_attack,_but_shark_involvement_prior_to_death_was_not_confirmed','shark_involvement__questionable','shark_involvement_not_confirmed,_injury_may_have_been_caused_by_a_bluefish','questionable_incident_-_shark_bite_may_have_precipitated_drowning','invalid_incident','questionable_incident;_reported_as_shark_attack_but_thought_to_involve_a_pinniped_instead_','considered_a_"doubtful"_incident','salmon_shark_suspected,_but_unlikely',"questionable_incident,_said_to_involve_a_6'_shark",'shark_involvement_prior_to_death_could_not_be_determined','shark_involvement_suspected_but_not_confirmed','shark_involvement_prior_to_death_remains_unconfirmed'],'invalid')

for i in range(data.shape[0]):
    if data.Species.loc[i]=='invalid':
        data['Fatal_(Y/N)'].loc[i]='not_relevant'

White shark                                           4.705543
Shark involvement prior to death was not confirmed    3.031178
Invalid                                               2.944573
Shark involvement not confirmed                       2.540416
Tiger shark                                           2.107390
                                                        ...
60 cm [2'] captive shark                              0.028868
Shortfin mako shark, 175-lb                           0.028868
White shark, >6'                                      0.028868
 Wobbegong shark, 1.6 to 1.8m                         0.028868
Zambesi shark, 2m                                     0.028868
Name: Species, Length: 1549, dtype: float64

nb of missing values 2838

/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

# Cleaning Fatal column

In [22]:
def get_basic_info_for_column(data,col):
    #check frequency of each element of the column (in %)
    display(pd.Series(data[col]).value_counts(normalize=True)*100)
    #print the min and the max for numeric data
    if data[col].dtype=='float64' or  data[col].dtype=='int':
        print('Min & Max', min(data[col]), max(data[col]))
    #how many missing data in Year column?:
    print('nb of missing values' ,data[col].isnull().sum())
    return None
get_basic_info_for_column(data,'Fatal_(Y/N)' )

N               68.562730
Y               22.095818
not_relevant     8.043583
UNKNOWN          1.121615
 N               0.112162
M                0.016023
2017             0.016023
y                0.016023
N                0.016023
Name: Fatal_(Y/N), dtype: float64

nb of missing values 61

In [23]:
# clean "typo" errors
data['Fatal_(Y/N)']=data['Fatal_(Y/N)'].str.upper().replace([' N','N ','M'],'N')

In [25]:

#provide injuries description for NAN in Fatal column and depending on the description I assign Y, N or UNKNOWN in FATAL
data[data['Fatal_(Y/N)'].isnull()].Injury.to_dict()

{27: 'Multiple severe injuries to arms and leg, leg subsequently surgically amputated',
 76: 'FATAL',
 84: 'FATAL, but death was probably due to drowning',
 107: 'Abrasions and cuts to sole of foot',
 125: 'Arm injured by hook, not by a shark',
 145: 'Laceration to thigh, likely caused by surfboard fin',
 151: 'Alleged laceration to left ankle',
 187: 'No attack, shark made a threat display',
 206: 'Shark breached cage, no injury to diver',
 265: 'No injury, board damaged',
 269: 'No injury, but sharks repeatedly hit their fins and guns',
 291: 'Fell off board when spinner shark leapt from the water next to him. No injury to surfer',
 382: 'Injury to hand',
 466: 'Minor cuts on feet',
 708: 'No injury, a 3 m blue shark merely snapped at the man.',
 763: 'Probable drowning with post-mortem bite',
 768: 'Cause of death was drowning & preceded shark involvement',
 814: 'Harassed by sharks but not injured by them',
 940: "Apparent drowning, and subsequent scavenging by 16' tiger shark",
 1118: '2-inch laceration to upper left arm',
 1271: 'As he pushd the shark away from his camera, his finger was cut on a tooth',
 1292: "No injury, captive shark attempted to bite diver's arm PROVOKED INCIDENTt",
 1304: 'Lacerations to left forearm',
 1410: 'No injury',
 1581: 'Dorsum of foot/ankle  injured by surfboard skeg or other inanimate object.',
 1805: 'Foot lacerated',
 1879: 'PRESUMED FATAL, body not recovered',
 1893: 'No injury, fell off ski after possibly colliding with  a shark',
 2025: 'Non-fatal',
 2684: 'Doubtful incident, needs investigation',
 2791: 'FATAL',
 2875: '10" laceration on leg',
 2975: 'Laceration to left thigh',
 3080: 'Knee bitten',
 3148: 'Missing, believed taken by a shark',
 3468: 'No injury',
 3506: 'Diver shot the shark, then it injured his arm and broke his leg with its tail.  PROVOKED INCIDENT',
 4011: 'Left forearm lacerated',
 4127: 'Boat damaged',
 4213: 'FATAL, but was it an accident or infanticide?',
 4333: 'No injury to occupants. Shark tore nets & trawl and struck boat repeatedly',
 4491: 'No injury from shark, scraped chest climbing out on reef',
 4504: 'No injury',
 4634: 'Probable drowning & scavenging',
 5100: "Thumb & coat sleeve recovered from shark's gut",
 5149: 'No injury',
 5210: 'Although this incident is listed elsewhere as a shark attack, the account of the disaster suggests the 4 who perished probably drowned. Five people survived',
 5302: 'No attack,  no injury',
 5329: 'Fatal, drowning or scavenging',
 5489: 'Probable drowning & scavenging. ',
 5895: 'No injury, but according to Fosdyk, captain & crew were killed by sharks',
 5906: 'FATAL',
 5918: 'Shark bit canoe in half & bit man. Note: There is an earlier story of FATAL shark attack in same river',
 5945: 'No injury',
 5988: 'Thought to have been taken by a shark/s. Bodies not  recovered',
 6071: '"Drowned, 2 days later his head was bitten off by a shark"',
 6104: 'FATAL',
 6122: 'Probable drowning & scavenging',
 6125: 'Shark scavenged on the dead sailors',
 6147: 'Lacerations to arm & leg',
 6158: 'Struck on thigh'}

In [26]:
#provide injuries description for 'UNKNOWN' in Fatal column and depending on the description I assign Y, N or UNKNOWN in FATAL                         
data[data['Fatal_(Y/N)']=='UNKNOWN'].Injury.to_dict()

#left to unknonwn after reading the injury description

{624: 'No details',
 1270: nan,
 2250: nan,
 2260: 'No details',
 2267: nan,
 2295: 'No details',
 2307: 'No details',
 2323: 'No details',
 2328: 'No details',
 2388: 'No details',
 2404: 'No details',
 2409: 'No details',
 2648: nan,
 2650: 'No details, "recovering in Darwin Hospital"',
 2661: 'No details',
 2806: 'No details',
 2882: 'No details',
 2900: 'No details',
 2943: 'No details',
 2996: 'No details',
 2998: 'No details',
 3006: 'No details',
 3038: nan,
 3041: 'No details',
 3298: nan,
 3396: 'No details',
 3411: 'No details',
 3429: 'No details',
 3434: nan,
 3507: 'No details, listed as PROVOKED INCIDENT',
 3545: 'No details',
 3552: 'Involved a speared shark but no other details PROVOKED INCIDENT',
 3712: nan,
 3774: 'No details',
 3794: 'Details unknown, possibly a PROVOKED INCIDENT',
 3838: nan,
 3841: nan,
 4060: nan,
 4208: 'Man landed at Cape Levêque lighthouse in critical condition after being bitten by a shark. Not known if he survived.',
 4256: 'No details',
 4269: 'No details',
 4310: 'No details',
 4323: 'No details',
 4517: nan,
 4689: 'Unprovoked, but circumstances unknown',
 4786: 'No details',
 4787: 'No details',
 4976: nan,
 4998: 'No details',
 5029: 'No details',
 5159: 'No details',
 5347: 'No details',
 5409: 'Calf removed, not known if he survived ',
 5555: 'No injury',
 5615: 'No details',
 5653: 'No injury',
 5656: '"Painfully injured" but no details',
 5674: 'No details',
 5708: 'No details',
 5709: 'No details',
 5998: 'Severe bite to thigh. Not known if he survived',
 6081: 'No details, it was the year the first settlers came ashore in Holdfast Bay, Port Pirie',
 6153: nan,
 6165: nan,
 6166: nan,
 6167: nan,
 6169: 'Leg severed mid-thigh, hand severed, arm above elbow and part of buttocks. Not known if he survived',
 6171: nan,
 6172: nan,
 6277: nan}

In [ ]:
# Area for single row check

In [ ]:
data.Injury.loc[532]

In [ ]:
data.loc[5895]

In [ ]:
data[data['Fatal_(Y/N)']=='2017'].Injury

In [ ]:
# Area for implemented changes once validated

In [27]:

#changing values to 'N', Y or UNKNOWN or not_relevant after checking the documentation and the injuries
data['Fatal_(Y/N)'].loc[786]='N'
data['Fatal_(Y/N)'].loc[[27,107,115,187,206,265,269,291,382,466,708,6158,5945,814,1118,1271,1292,1304,1410,1805,1893,2025,2875,2975,3080,3468,4011,4127,4333,4504,5149]]='N'
data['Fatal_(Y/N)'].loc[[76,6147,6104,5906,2791]]='Y'
data['Fatal_(Y/N)'].loc[[5918,1879]]='UNKNOWN'
data['Fatal_(Y/N)'].loc[[84,125,145,151,6125,6122,6071,5988,763,768,940,1581,2684,3506,4491,4634,5100,5210,5302,5329,5484,3148,4213,5895,5489]]='NOT_RELEVANT'
get_basic_info_for_column(data,'Fatal_(Y/N)' )

N               68.549667
Y               21.961282
NOT_RELEVANT     8.346557
UNKNOWN          1.142494
Name: Fatal_(Y/N), dtype: float64

nb of missing values 0

In [ ]:
data.loc[786]

In [28]:
# select only the relevant part of fatal for the rest of the cleaning.
data=data[data['Fatal_(Y/N)']!='NOT_RELEVANT']

# Cleaning of column Year

In [30]:
get_basic_info_for_column(data,'Year')

2015.0    2.268791
2017.0    2.182196
2016.0    2.130239
0.0       2.130239
2011.0    2.026325
            ...
1791.0    0.017319
1815.0    0.017319
1807.0    0.017319
1786.0    0.017319
1764.0    0.017319
Name: Year, Length: 244, dtype: float64

Min & Max 0.0 2018.0
nb of missing values 2

In [33]:
# isolate missing values in column Year and display the associated rows
data[data.Year.isnull()]
# 2 rows concerned: n87 and 6079.
# First find the year using the  reported date 
#check whether other field in the row have an issue, especially the columns you are interested in  and clean them if possible
# at the same time
#Second use the pdf to fill in the missing information if necessary.

,Case_Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator_Or_Source,Pdf,Href_Formula,Href,Case_Number1,Case_Number2,Original_Order,Unnamed_22,Unnamed_23
187,2017.01.08.R,Reported 08-Jan-2017,NaN,Invalid,AUSTRALIA,Queensland,NaN,Spearfishing,Kerry Daniel,M,...,bull_shark,Liquid Vision 1/8/2017,2017.01.08.R-KerryDaniel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.01.08.R,2017.01.08.R,6116.0,NaN,NaN
6079,1836.08.19.R,Reported 19-Aug-1836,NaN,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,...,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,224.0,NaN,NaN

In [35]:
# Area to implement validated changes

In [37]:
data.Year.loc[187]=2017
data.Year.loc[6079]=1836
#check if there are still missing values
data[data.Year.isnull()]
#drop remaining rows by selecting the none null values of years
data=data[data.Year.notnull()]
# select the Year =0
data[data.Year==0] # 125 rows with a year =0 vs 6300 records. 1%. To be treated if sufficient time
# display date column  for Year =0 to see wether the year appear in the date
pd.Series(data[data.Year==0].Date).value_counts() # compare with the year of full set. 
#Check the number of rows if we do buckets like 'before 1960 (2500 rows more than 1/3 of therows , before 1920)
# 125 rows with no exact date no change for the moment . Doing
data[data.Year==0].Date.to_dict() # put the date for Year ==0 to see whether some records could be treated

/usr/local/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

{6177: 'Ca. 214 B.C.',
 6178: 'Ca. 336.B.C..',
 6179: '493 B.C.',
 6180: 'Ca. 725 B.C.',
 6181: 'Before 1939',
 6182: '1990 or 1991',
 6183: 'Before 2016',
 6184: 'Before Oct-2009',
 6185: 'Before 1934',
 6186: 'Before 1934',
 6187: '2009?',
 6188: 'Before 1930',
 6189: '1880-1899',
 6190: 'Before 1909',
 6191: 'Before 2012',
 6192: 'Before 1916',
 6193: 'Between   1951-1963',
 6194: 'Before 1908',
 6195: 'Before 1900',
 6196: 'Before 1876',
 6197: 'Before 2012',
 6198: 'Before 2011',
 6199: 'Before 2011',
 6200: 'Before 2009',
 6201: 'Beforer 1994',
 6202: 'Before 1963',
 6203: '1896-1913',
 6204: 'Before 1936',
 6205: 'Before 08-Jun-1912',
 6206: 'Before 2012',
 6207: 'Before 1911',
 6208: 'Before 1901',
 6209: 'No date, late 1960s',
 6210: 'Before 2006',
 6211: 'Before 2003',
 6212: 'Before 2004',
 6213: 'Before 1962',
 6214: '1950s',
 6215: 'No date, Before 1963',
 6216: '2003?',
 6217: 'No date',
 6218: 'No date',
 6219: 'Before Feb-1998',
 6220: 'No date, Before May-1996',
 6221: 'No date, Before Mar-1995',
 6222: 'Before 1996',
 6223: 'No date, Before Aug-1989',
 6224: 'No date, Before Aug-1987',
 6225: 'No date, Before 1987',
 6226: 'No date, Before  1975',
 6228: 'No date, Before 1969',
 6229: 'No date, Before 3-Jan-1967',
 6230: 'No date, Before 1963',
 6231: 'No date, Before 8-May-1965',
 6233: 'No date, Before 1902',
 6234: 'No date, Before 1902',
 6235: 'No date, Before 1963',
 6236: 'No date, After August 1926 and before 1936',
 6237: 'No date, Before 1963',
 6238: 'Before 1962',
 6239: 'Before 1962',
 6240: 'Before 1961',
 6241: '1960s',
 6242: '1960s',
 6243: '1960s',
 6244: 'Before 1960',
 6245: 'Before  19-Jun-1959',
 6246: 'Before  24 Apr-1959',
 6247: 'Before  1958',
 6248: 'Before  1958',
 6249: 'Before 1958',
 6250: 'Before 1958',
 6251: 'Before 1958',
 6252: 'Before 1958',
 6253: 'Before 1957',
 6254: 'Before 1957',
 6255: 'Before 1956',
 6256: 'Before 1956',
 6257: 'Before Mar-1956',
 6258: 'Before 1952',
 6259: '1941-1945',
 6260: '"During the war" 1943-1945',
 6261: '"Before the war"',
 6262: 'Said to be 1941-1945, more likely 1945',
 6263: '1941-1945',
 6264: '1941-1945',
 6265: '1941-1942',
 6266: '1940 - 1950',
 6267: '1940 - 1950',
 6268: '1940 - 1950',
 6269: '1940-1946',
 6270: 'Before 1905',
 6271: 'World War II',
 6272: 'World War II',
 6273: 'Before 1905',
 6274: 'A few years before 1938',
 6275: 'No date',
 6276: 'Early 1930s',
 6277: 'Before 1927',
 6278: 'Between 1918 & 1939',
 6279: 'No date',
 6280: 'No date',
 6281: 'No date',
 6282: '1920 -1923',
 6283: 'Before 1921',
 6284: 'Before 1911',
 6285: 'Before 1921',
 6286: 'Before 1921',
 6287: 'Before 1917',
 6288: 'Before 17-Jul-1916',
 6289: 'No date (3 days after preceding incident) & prior to 19-Jul-1913',
 6290: 'Before 19-Jul-1913',
 6291: 'Before 1911',
 6292: 'Circa 1862',
 6293: 'Before 1906',
 6294: 'Before 1906',
 6295: 'Before 1906',
 6296: 'Before 1906',
 6297: 'Before 1903',
 6298: 'Before 1903',
 6299: '1900-1905',
 6300: '1883-1889',
 6301: '1845-1853'}

# Country column cleaning

In [29]:
get_basic_info_for_column(data,'Country' )

USA                           35.607118
AUSTRALIA                     21.441033
SOUTH AFRICA                   9.019539
PAPUA NEW GUINEA               2.285415
NEW ZEALAND                    2.023726
                                ...
UNITED ARAB EMIRATES (UAE)     0.017446
ALGERIA                        0.017446
MALDIVE ISLANDS                0.017446
GHANA                          0.017446
OCEAN                          0.017446
Name: Country, Length: 203, dtype: float64

nb of missing values 44

In [ ]:
# clean "typo" errors
data['Country']=data['Country'].str.upper().replace([' '],'_')
pd.Series(data['Country']).value_counts().to_dict()

# Helpfull formulas

In [ ]:
# vérifier s'il y a des donnees manquantes dans les colonnes
initial_data.columns[initial_data.isnull().any()]

In [ ]:
new_data[new_data["Year"] < 1920]

In [ ]:
# Replace NaN float to integer 0 in numeric table
#new_data['Year'].apply(int)

In [ ]:
new_data['href formula'].iloc[187]

In [ ]:
new_data[new_data.Year.isnull()]

In [ ]:
new_data.iloc[6079]

In [ ]:
new_data.Year.iloc[1]

In [ ]:
new_data['href'].iloc[6079]

In [ ]:
#appeler les lignes pour lesquelles year =1999
set=new_data[new_data["Year"] == 1999]

In [ ]:
pd.Series(list(new_data.columns)).str.lower().str.title().str.replace(' ','_').str.replace('Sex_','Sex').str.replace('Species_','Species')

In [ ]:
#Nbre de données manquantes par colonne/ Doublon avec infor
# Number of missing values per column . Other way to read 

initial_data.isnull().sum(axis=1)
# Lots of null values in all the columns==> there may be null rows
# columns named Case Number+> check whether there are the same or not
# 2 Unnamed colums with almost no values . Check whether they can be deleted.
# Can species and time and age  be used given the high level of missingg data?

In [ ]:
# filter the rows with less than two non "null" columns.
# a column is null if it equals Nan, '', 0 or '0'
import numpy as np
data[data.replace(['', 0, '0'], np.nan).isnull().sum(axis=1) <= len(data.columns) - 2]

In [ ]:
#Delete all rows with missing values for all rows
data=initial_data.dropna(axis=0,how='all')
data.shape # 8703 rows remain out of 25723. displaying data I notice that there where case number at 0 with no information
#remove empty rows ignoring the column case number
data.columns
data.dropna(axis=0,how='all',subset=['Date', 'Year', 'Type', 'Country', 'Area', 'Location','Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal_(Y/N)', 'Time','Species', 'Investigator_Or_Source', 'Pdf', 'Href_Formula', 'Href','Case_Number1', 'Case_Number2', 'Original_Order', 'Unnamed_22','Unnamed_23'])
#remove empty rows ignoring the column 'case number1' as there are rows with only  one value in this colon

In [ ]:
data.columns

In [ ]:
#data.plot(kind="bar", x="Fatal_(Y/N)",y="Count")